### PR TITLE
Dark mode charts + resizing fixes

### LINKED ISSUE #307: Fix charting components resizing to disallowed sizes

### PR DESCRIPTION
**Pull request by pierce-smith1**
All charts should now respect dark mode (#308). In doing this, I also had to fix #307, so you get it for free.
Also, lag on the client should be reduced, especially in COVID charts, since queries no longer happen every 2 seconds. Now that timer runs every 1.5 seconds and only does re-rendering of chart frames, nothing more.

### CODE REVIEW

File: src/js/library/charting/chartSystem.js [hunk 1]
```diff
@@ -232,7 +222,7 @@ export default class ChartSystem {
     }
 
     initializeUpdateHooks() {
-        this.map.on('moveend', e => { 
+        this.map.on('move', e => {
```
Comment (pierce-smith1) [inline src/js/library/charting/chartSystem.js:225]: I changed this back because, with `moveend`, the charts do not update seamlessly as you drag the map around, which I think would disappoint Shrideep. 
To prevent queries from getting spammed there's an enforced 0.2 second delay between updates, which has existed for a little while and is not new in this PR (so you won't see it in diffs).
Let me know how you feel about this.

**Review by drg101 — APPROVED** [review]
Everything works good, 0.2s seems fine and doesn't lag anything out for me.
